version: '3'
services:
  alembic:
    image: username502/sputnik_bot:latest
    env_file:
      - none.env
    environment:
      - ENVIRONMENT
      - WORKERS
      - TIME_OUT
      - BOT_TOKEN
      - BOT_SECRET_URL
      - BOT_WEB_HOOK
      - RSS_FEED
      - SHORT_LINK
      - WEIBO_APP_KEY
      - WEIBO_APP_SECRET
      - WEIBO_APP_HOST
      - WEIBO_LOGIN
      - WEIBO_PASSWORD
      - WEIBO_TEST_LOGIN
      - WEIBO_TEST_PASSWORD
      - DB_DSN
      - POST_USER
      - ADMIN_USER
      - WHITE_LIST_USER
      - JWT_SECRET
      - ANTI_CAPTCHA_KEY
      - UPDATE_POST_SECONDS
      - SEND_POST_SECONDS
      - WEIBO_HOST_URL
      - WEIBO_NICK
      - DRONE_COMMIT
    command: alembic upgrade heads
  bot:
    image: username502/sputnik_bot:latest
    restart: always
    expose:
      - "8080"
    env_file:
      - none.env
    environment:
      - ENVIRONMENT
      - WORKERS
      - TIME_OUT
      - BOT_TOKEN
      - BOT_SECRET_URL
      - BOT_WEB_HOOK
      - RSS_FEED
      - SHORT_LINK
      - WEIBO_APP_KEY
      - WEIBO_APP_SECRET
      - WEIBO_APP_HOST
      - WEIBO_LOGIN
      - WEIBO_PASSWORD
      - WEIBO_TEST_LOGIN
      - WEIBO_TEST_PASSWORD
      - DB_DSN
      - POST_USER
      - ADMIN_USER
      - WHITE_LIST_USER
      - JWT_SECRET
      - ANTI_CAPTCHA_KEY
      - UPDATE_POST_SECONDS
      - SEND_POST_SECONDS
      - WEIBO_HOST_URL
      - WEIBO_NICK
      - DRONE_COMMIT
    command: python manage.py api
    depends_on:
      - alembic
  scheduler:
    image: username502/sputnik_bot:latest
    restart: always
    expose:
      - "8081"
    environment:
      - ENVIRONMENT
      - WORKERS
      - TIME_OUT
      - BOT_TOKEN
      - BOT_SECRET_URL
      - BOT_WEB_HOOK
      - RSS_FEED
      - SHORT_LINK
      - WEIBO_APP_KEY
      - WEIBO_APP_SECRET
      - WEIBO_APP_HOST
      - WEIBO_LOGIN
      - WEIBO_PASSWORD
      - WEIBO_TEST_LOGIN
      - WEIBO_TEST_PASSWORD
      - DB_DSN
      - POST_USER
      - ADMIN_USER
      - WHITE_LIST_USER
      - JWT_SECRET
      - ANTI_CAPTCHA_KEY
      - UPDATE_POST_SECONDS
      - SEND_POST_SECONDS
      - WEIBO_HOST_URL
      - WEIBO_NICK
      - DRONE_COMMIT
    env_file:
      - none.env
    command: python manage.py schedule
    depends_on:
      - alembic
  nginx:
    image: umputun/nginx-le:latest
    restart: always
    volumes:
      - /srv/docker/ssl:/etc/nginx/ssl
      - ./nginx/app.conf:/etc/nginx/service.conf
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=GMT
      - LETSENCRYPT=true
      - LE_EMAIL=skar404@gamil.com
      - LE_FQDN=sputnik.bot.assa.dev
    depends_on:
      - bot
