"""add column is_posted

Revision ID: 3e3bd0abd38b
Revises: c66ccbe77e89
Create Date: 2019-04-09 01:03:20.092777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3bd0abd38b'
down_revision = 'c66ccbe77e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_posted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_post_is_posted'), 'post', ['is_posted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_is_posted'), table_name='post')
    op.drop_column('post', 'is_posted')
    # ### end Alembic commands ###
