name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build imag
      run: |
        docker login docker.pkg.github.com --username skar404
        docker build . -t docker.pkg.github.com/skar404/sputnik_bot/app:1.0 
        docker push docker.pkg.github.com/skar404/sputnik_bot/app:1.0

